using System;

namespace PeakBadgeHandbook
{
    // 内嵌默认徽章/外观/成就 JSON（旧版 HandbookExport 数据快照，作为缺失/损坏时的兜底）。
    // 维护提示：每次发布新版本前，用最新提取数据重新生成本文件。
    public static class EmbeddedData
    {
        public const string BadgesJson = @"[
  {
    ""visualID"": 25,
    ""displayName"": ""Participation"",
    ""description"": ""Have a friend escape the island without you."",
    ""achievementType"": ""TriedYourBestBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_25.png""
  },
  {
    ""visualID"": 22,
    ""displayName"": ""Endurance"",
    ""description"": ""Climb 50m upwards without touching the ground."",
    ""achievementType"": ""EnduranceBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_22.png""
  },
  {
    ""visualID"": 32,
    ""displayName"": ""Nomad"",
    ""description"": ""Climb past the MESA."",
    ""achievementType"": ""NomadBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_32.png""
  },
  {
    ""visualID"": 38,
    ""displayName"": ""Ultimate"",
    ""description"": ""Catch a Flying Disc from 50m away."",
    ""achievementType"": ""UltimateBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_38.png""
  },
  {
    ""visualID"": 37,
    ""displayName"": ""Cool Cucumber"",
    ""description"": ""Climb past the MESA without ever having more than 10% Heat."",
    ""achievementType"": ""CoolCucumberBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_37.png""
  },
  {
    ""visualID"": 36,
    ""displayName"": ""Needlepoint"",
    ""description"": ""Have a lot of cactuses stuck to you."",
    ""achievementType"": ""NeedlepointBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_36.png""
  },
  {
    ""visualID"": 34,
    ""displayName"": ""Aeronautics"",
    ""description"": ""Achieve flight."",
    ""achievementType"": ""AeronauticsBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_34.png""
  },
  {
    ""visualID"": 33,
    ""displayName"": ""24 Karat"",
    ""description"": ""Offer The Kiln a worthy sacrifice."",
    ""achievementType"": ""TwentyFourKaratBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_33.png""
  },
  {
    ""visualID"": 40,
    ""displayName"": ""Resourcefulness"",
    ""description"": ""Give in to your hunger."",
    ""achievementType"": ""ResourcefulnessBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_40.png""
  },
  {
    ""visualID"": 41,
    ""displayName"": ""Daredevil"",
    ""description"": ""Shoot across the MESA canyon in a Scout Cannon."",
    ""achievementType"": ""DaredevilBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_41.png""
  },
  {
    ""visualID"": 35,
    ""displayName"": ""Megaentomology"",
    ""description"": ""Survive an Antlion attack."",
    ""achievementType"": ""MegaentomologyBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_35.png""
  },
  {
    ""visualID"": 39,
    ""displayName"": ""Astronomy"",
    ""description"": ""Look a little too closely at the blazing sun."",
    ""achievementType"": ""AstronomyBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_39.png""
  },
  {
    ""visualID"": 42,
    ""displayName"": ""Bundled Up"",
    ""description"": ""Climb past the ALPINE without ever having more than 20% Cold."",
    ""achievementType"": ""BundledUpBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_42.png""
  },
  {
    ""visualID"": 43,
    ""displayName"": ""Forestry"",
    ""description"": ""Climb past the ROOTS."",
    ""achievementType"": ""ForestryBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_43.png""
  },
  {
    ""visualID"": 44,
    ""displayName"": ""Tread Lightly"",
    ""description"": ""Climb past the ROOTS without ever having more than 25% spores."",
    ""achievementType"": ""TreadLightlyBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_44.png""
  },
  {
    ""visualID"": 45,
    ""displayName"": ""Web Security"",
    ""description"": ""Survive getting caught in a spider's web."",
    ""achievementType"": ""WebSecurityBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_45.png""
  },
  {
    ""visualID"": 46,
    ""displayName"": ""Undead Encounter"",
    ""description"": ""Cure yourself from a zombie bite."",
    ""achievementType"": ""UndeadEncounterBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_46.png""
  },
  {
    ""visualID"": 47,
    ""displayName"": ""Advanced Mycology"",
    ""description"": ""Try all 5 types of Shroomberry in a run."",
    ""achievementType"": ""AdvancedMycologyBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_47.png""
  },
  {
    ""visualID"": 48,
    ""displayName"": ""Disaster Response"",
    ""description"": ""Pull a passed out friend Xm with the Rescue Claw."",
    ""achievementType"": ""DisasterResponseBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_48.png""
  },
  {
    ""visualID"": 49,
    ""displayName"": ""Calcium Intake"",
    ""description"": ""Block 100 total damage with the Fortified Milk."",
    ""achievementType"": ""CalciumIntakeBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_49.png""
  },
  {
    ""visualID"": 50,
    ""displayName"": ""Competitive Eating"",
    ""description"": ""Eat 5 Hot Dogs."",
    ""achievementType"": ""CompetitiveEatingBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_50.png""
  },
  {
    ""visualID"": 51,
    ""displayName"": ""Applied Esoterica"",
    ""description"": ""Ressurect a friend using unholy means."",
    ""achievementType"": ""AppliedEsotericaBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_51.png""
  },
  {
    ""visualID"": 52,
    ""displayName"": ""Mycoacrobatics"",
    ""description"": ""Bounce up Xm off a mushroom."",
    ""achievementType"": ""MycoacrobaticsBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_52.png""
  },
  {
    ""visualID"": 53,
    ""displayName"": ""Cryptogastronomy"",
    ""description"": ""Cook and eat a Mandrake."",
    ""achievementType"": ""CryptogastronomyBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_53.png""
  },
  {
    ""visualID"": 54,
    ""displayName"": ""Wanderer"",
    ""description"": ""Climb past the GLOOM."",
    ""achievementType"": ""WandererBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_54.png""
  },
  {
    ""visualID"": 55,
    ""displayName"": ""Bellringer"",
    ""description"": ""Ring 5 Belltowers in the Gloom in a single run."",
    ""achievementType"": ""BellringerBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_55.png""
  },
  {
    ""visualID"": 56,
    ""displayName"": ""Well Rested"",
    ""description"": ""Consume The Early Worm."",
    ""achievementType"": ""WellRestedBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_56.png""
  },
  {
    ""visualID"": 57,
    ""displayName"": ""Jester"",
    ""description"": ""Open 3 Clown Luggage in one run."",
    ""achievementType"": ""JesterBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_57.png""
  },
  {
    ""visualID"": 58,
    ""displayName"": ""Hang Gliding"",
    ""description"": ""Fly 100m with the Glider without touching the ground."",
    ""achievementType"": ""HangGlidingBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_58.png""
  },
  {
    ""visualID"": 59,
    ""displayName"": ""Medieval History"",
    ""description"": ""Climb past THE CITADEL without being hit by any traps."",
    ""achievementType"": ""MedievalHistoryBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_59.png""
  },
  {
    ""visualID"": 60,
    ""displayName"": ""Last Resort"",
    ""description"": ""Heal over 75% damage at once by using the Ritual Dagger."",
    ""achievementType"": ""LastResortBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_60.png""
  },
  {
    ""visualID"": 61,
    ""displayName"": ""Exorcist"",
    ""description"": ""Burn up the Big Ghost in the GLOOM."",
    ""achievementType"": ""ExorcistBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_61.png""
  },
  {
    ""visualID"": 62,
    ""displayName"": ""Archery"",
    ""description"": ""Remove 10 arrows from yourself in one run."",
    ""achievementType"": ""ArcheryBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_62.png""
  },
  {
    ""visualID"": 63,
    ""displayName"": ""Rule Zero"",
    ""description"": ""Free the Scoutmaster's soul."",
    ""achievementType"": ""RuleZeroBadge"",
    ""secret"": true,
    ""testLocked"": false,
    ""iconFile"": ""badge_63.png""
  },
  {
    ""visualID"": 3,
    ""displayName"": ""Alpinist"",
    ""description"": ""Climb past the ALPINE."",
    ""achievementType"": ""AlpinistBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_3.png""
  },
  {
    ""visualID"": 27,
    ""displayName"": ""Animal Serenading"",
    ""description"": ""Play the bugle for a capybara."",
    ""achievementType"": ""AnimalSerenadingBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_27.png""
  },
  {
    ""visualID"": 28,
    ""displayName"": ""Arborist"",
    ""description"": ""Reach the top of a really big tree."",
    ""achievementType"": ""ArboristBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_28.png""
  },
  {
    ""visualID"": 23,
    ""displayName"": ""High Altitude"",
    ""description"": ""Climb 5000m total."",
    ""achievementType"": ""AscenderBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_23.png""
  },
  {
    ""visualID"": 18,
    ""displayName"": ""BalloonBadge"",
    ""description"": ""Escape the island without taking fall damage."",
    ""achievementType"": ""BalloonBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_18.png""
  },
  {
    ""visualID"": 1,
    ""displayName"": ""Beachcomber"",
    ""description"": ""Climb past the SHORE."",
    ""achievementType"": ""BeachcomberBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_1.png""
  },
  {
    ""visualID"": 12,
    ""displayName"": ""BingBongBadge"",
    ""description"": ""Help Bing Bong escape the island."",
    ""achievementType"": ""BingBongBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_12.png""
  },
  {
    ""visualID"": 20,
    ""displayName"": ""Bookworm"",
    ""description"": ""Read all of Scoutmaster Myres's journal entries."",
    ""achievementType"": ""BookwormBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_20.png""
  },
  {
    ""visualID"": 24,
    ""displayName"": ""Bouldering"",
    ""description"": ""Place 10 pitons."",
    ""achievementType"": ""BoulderingBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_24.png""
  },
  {
    ""visualID"": 13,
    ""displayName"": ""Clutch"",
    ""description"": ""Resurrect 3 scouts in a single expedition. "",
    ""achievementType"": ""ClutchBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_13.png""
  },
  {
    ""visualID"": 7,
    ""displayName"": ""Cooking"",
    ""description"": ""Cook 20 meals at campfires."",
    ""achievementType"": ""CookingBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_7.png""
  },
  {
    ""visualID"": 17,
    ""displayName"": ""Emergency Preparedness"",
    ""description"": ""Heal an unconscious friend with an item to save them from death."",
    ""achievementType"": ""EmergencyPreparednessBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_17.png""
  },
  {
    ""visualID"": 21,
    ""displayName"": ""Esoterica"",
    ""description"": ""Obtain a mystical item."",
    ""achievementType"": ""EsotericaBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_21.png""
  },
  {
    ""visualID"": 8,
    ""displayName"": ""First Aid"",
    ""description"": ""Heal your friends for 100 points of injury in a single expedition."",
    ""achievementType"": ""FirstAidBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_8.png""
  },
  {
    ""visualID"": 16,
    ""displayName"": ""Foraging"",
    ""description"": ""Eat 5 different berries in a single expedition."",
    ""achievementType"": ""ForagingBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_16.png""
  },
  {
    ""visualID"": 31,
    ""displayName"": ""Gourmand"",
    ""description"": ""Escape the island after cooking and eating a coconut half, a honeycomb, a yellow winterberry, and an egg."",
    ""achievementType"": ""GourmandBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_31.png""
  },
  {
    ""visualID"": 29,
    ""displayName"": ""Happy Camper"",
    ""description"": ""Receive 5 Morale Boosts from campfires."",
    ""achievementType"": ""HappyCamperBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_29.png""
  },
  {
    ""visualID"": 6,
    ""displayName"": ""Knot Tying"",
    ""description"": ""Place 100m of rope in a single expedition."",
    ""achievementType"": ""KnotTyingBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_6.png""
  },
  {
    ""visualID"": 11,
    ""displayName"": ""Leave No Trace"",
    ""description"": ""Escape the island without placing anything on the mountain."",
    ""achievementType"": ""LeaveNoTraceBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_11.png""
  },
  {
    ""visualID"": 26,
    ""displayName"": ""Lone Wolf"",
    ""description"": ""Escape the island in a solo expedition."",
    ""achievementType"": ""LoneWolfBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_26.png""
  },
  {
    ""visualID"": 10,
    ""displayName"": ""Mentorship"",
    ""description"": ""Have a 1-on-1 with the Scoutmaster."",
    ""achievementType"": ""MentorshipBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_10.png""
  },
  {
    ""visualID"": 9,
    ""displayName"": ""Mycology"",
    ""description"": ""Eat four different non-toxic mushrooms in a single expedition."",
    ""achievementType"": ""MycologyBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_9.png""
  },
  {
    ""visualID"": 30,
    ""displayName"": ""Naturalist"",
    ""description"": ""Escape the island without eating any packaged food."",
    ""achievementType"": ""NaturalistBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_30.png""
  },
  {
    ""visualID"": 0,
    ""displayName"": ""Peakbadge"",
    ""description"": ""Reach the PEAK."",
    ""achievementType"": ""PeakBadge"",
    ""secret"": false,
    ""testLocked"": true,
    ""iconFile"": ""badge_0.png""
  },
  {
    ""visualID"": 19,
    ""displayName"": ""Plunderer"",
    ""description"": ""Open 15 luggages in a single expedition."",
    ""achievementType"": ""PlundererBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_19.png""
  },
  {
    ""visualID"": 15,
    ""displayName"": ""Hasty"",
    ""description"": ""Escape the island in under an hour."",
    ""achievementType"": ""SpeedClimberBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_15.png""
  },
  {
    ""visualID"": 5,
    ""displayName"": ""Survivalist"",
    ""description"": ""Escape the island without ever losing consciousness."",
    ""achievementType"": ""SurvivalistBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_5.png""
  },
  {
    ""visualID"": 14,
    ""displayName"": ""Toxicology"",
    ""description"": ""Restore 200 total poison by using items. "",
    ""achievementType"": ""ToxicologyBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_14.png""
  },
  {
    ""visualID"": 2,
    ""displayName"": ""Trailblazer"",
    ""description"": ""Climb past the TROPICS."",
    ""achievementType"": ""TrailblazerBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_2.png""
  },
  {
    ""visualID"": 4,
    ""displayName"": ""Volcanology"",
    ""description"": ""Climb past the CALDERA."",
    ""achievementType"": ""VolcanologyBadge"",
    ""secret"": false,
    ""testLocked"": false,
    ""iconFile"": ""badge_4.png""
  }
]";

        public const string CosmeticsJson = @"[
  {
    ""slot"": ""skins"",
    ""index"": 0,
    ""textureFile"": ""skins_0.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""skins"",
    ""index"": 1,
    ""textureFile"": ""skins_1.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""skins"",
    ""index"": 2,
    ""textureFile"": ""skins_2.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""skins"",
    ""index"": 3,
    ""textureFile"": ""skins_3.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""skins"",
    ""index"": 4,
    ""textureFile"": ""skins_4.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""skins"",
    ""index"": 5,
    ""textureFile"": ""skins_5.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""skins"",
    ""index"": 6,
    ""textureFile"": ""skins_6.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""skins"",
    ""index"": 7,
    ""textureFile"": ""skins_7.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""skins"",
    ""index"": 8,
    ""textureFile"": ""skins_8.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 0,
    ""textureFile"": ""eyes_0.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 1,
    ""textureFile"": ""eyes_1.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 2,
    ""textureFile"": ""eyes_2.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 3,
    ""textureFile"": ""eyes_3.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 4,
    ""textureFile"": ""eyes_4.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 5,
    ""textureFile"": ""eyes_5.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 6,
    ""textureFile"": ""eyes_6.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 7,
    ""textureFile"": ""eyes_7.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 8,
    ""textureFile"": ""eyes_8.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 9,
    ""textureFile"": ""eyes_9.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 10,
    ""textureFile"": ""eyes_10.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 11,
    ""textureFile"": ""eyes_11.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 12,
    ""textureFile"": ""eyes_12.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 13,
    ""textureFile"": ""eyes_13.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 14,
    ""textureFile"": ""eyes_14.png"",
    ""requiredAchievement"": ""BoulderingBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 15,
    ""textureFile"": ""eyes_15.png"",
    ""requiredAchievement"": ""ArboristBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 16,
    ""textureFile"": ""eyes_16.png"",
    ""requiredAchievement"": ""GourmandBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""eyes"",
    ""index"": 17,
    ""textureFile"": ""eyes_17.png"",
    ""requiredAchievement"": ""MentorshipBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 0,
    ""textureFile"": ""mouths_0.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 1,
    ""textureFile"": ""mouths_1.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 2,
    ""textureFile"": ""mouths_2.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 3,
    ""textureFile"": ""mouths_3.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 4,
    ""textureFile"": ""mouths_4.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 5,
    ""textureFile"": ""mouths_5.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 6,
    ""textureFile"": ""mouths_6.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 7,
    ""textureFile"": ""mouths_7.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 8,
    ""textureFile"": ""mouths_8.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 9,
    ""textureFile"": ""mouths_9.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 10,
    ""textureFile"": ""mouths_10.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 11,
    ""textureFile"": ""mouths_11.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 12,
    ""textureFile"": ""mouths_12.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 13,
    ""textureFile"": ""mouths_13.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 14,
    ""textureFile"": ""mouths_14.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 15,
    ""textureFile"": ""mouths_15.png"",
    ""requiredAchievement"": ""ToxicologyBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 16,
    ""textureFile"": ""mouths_16.png"",
    ""requiredAchievement"": ""GourmandBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 17,
    ""textureFile"": ""mouths_17.png"",
    ""requiredAchievement"": ""ForagingBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""mouths"",
    ""index"": 18,
    ""textureFile"": ""mouths_18.png"",
    ""requiredAchievement"": ""ResourcefulnessBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 0,
    ""textureFile"": ""accessories_0.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 1,
    ""textureFile"": ""accessories_1.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 2,
    ""textureFile"": ""accessories_2.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 3,
    ""textureFile"": ""accessories_3.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 4,
    ""textureFile"": ""accessories_4.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 5,
    ""textureFile"": ""accessories_5.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 6,
    ""textureFile"": ""accessories_6.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 7,
    ""textureFile"": ""accessories_7.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 8,
    ""textureFile"": ""accessories_8.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 9,
    ""textureFile"": ""accessories_9.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 10,
    ""textureFile"": ""accessories_10.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 11,
    ""textureFile"": ""accessories_11.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 12,
    ""textureFile"": ""accessories_12.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 13,
    ""textureFile"": ""accessories_13.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 14,
    ""textureFile"": ""accessories_14.png"",
    ""requiredAchievement"": ""KnotTyingBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 15,
    ""textureFile"": ""accessories_15.png"",
    ""requiredAchievement"": ""PlundererBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 16,
    ""textureFile"": ""accessories_16.png"",
    ""requiredAchievement"": ""BookwormBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 17,
    ""textureFile"": ""accessories_17.png"",
    ""requiredAchievement"": ""LeaveNoTraceBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 18,
    ""textureFile"": ""accessories_18.png"",
    ""requiredAchievement"": ""AstronomyBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 19,
    ""textureFile"": ""accessories_19.png"",
    ""requiredAchievement"": ""MegaentomologyBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""accessories"",
    ""index"": 20,
    ""textureFile"": ""accessories_20.png"",
    ""requiredAchievement"": ""CalciumIntakeBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 0,
    ""textureFile"": ""fits_0.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 1,
    ""textureFile"": ""fits_1.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 2,
    ""textureFile"": ""fits_2.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 3,
    ""textureFile"": ""fits_3.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 4,
    ""textureFile"": ""fits_4.png"",
    ""requiredAchievement"": ""EmergencyPreparednessBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 5,
    ""textureFile"": ""fits_5.png"",
    ""requiredAchievement"": ""EmergencyPreparednessBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 6,
    ""textureFile"": ""fits_6.png"",
    ""requiredAchievement"": ""TriedYourBestBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 7,
    ""textureFile"": ""fits_7.png"",
    ""requiredAchievement"": ""TriedYourBestBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 8,
    ""textureFile"": ""fits_8.png"",
    ""requiredAchievement"": ""VolcanologyBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 9,
    ""textureFile"": ""fits_9.png"",
    ""requiredAchievement"": ""VolcanologyBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 10,
    ""textureFile"": ""fits_10.png"",
    ""requiredAchievement"": ""HappyCamperBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 11,
    ""textureFile"": ""fits_11.png"",
    ""requiredAchievement"": ""HappyCamperBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 12,
    ""textureFile"": ""fits_12.png"",
    ""requiredAchievement"": ""BalloonBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 13,
    ""textureFile"": ""fits_13.png"",
    ""requiredAchievement"": ""BalloonBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 14,
    ""textureFile"": ""fits_14.png"",
    ""requiredAchievement"": ""SurvivalistBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 15,
    ""textureFile"": ""fits_15.png"",
    ""requiredAchievement"": ""SurvivalistBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 16,
    ""textureFile"": ""fits_16.png"",
    ""requiredAchievement"": ""CoolCucumberBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 17,
    ""textureFile"": ""fits_17.png"",
    ""requiredAchievement"": ""AeronauticsBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 18,
    ""textureFile"": ""fits_18.png"",
    ""requiredAchievement"": ""AlpinistBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 19,
    ""textureFile"": ""fits_19.png"",
    ""requiredAchievement"": ""BundledUpBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 20,
    ""textureFile"": ""fits_20.png"",
    ""requiredAchievement"": ""BundledUpBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 21,
    ""textureFile"": ""fits_21.png"",
    ""requiredAchievement"": ""ForestryBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 22,
    ""textureFile"": ""fits_22.png"",
    ""requiredAchievement"": ""TreadLightlyBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 23,
    ""textureFile"": ""fits_23.png"",
    ""requiredAchievement"": ""WebSecurityBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 24,
    ""textureFile"": ""fits_24.png"",
    ""requiredAchievement"": ""DisasterResponseBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 25,
    ""textureFile"": ""fits_25.png"",
    ""requiredAchievement"": ""AppliedEsotericaBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 26,
    ""textureFile"": ""fits_26.png"",
    ""requiredAchievement"": ""MycoacrobaticsBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 27,
    ""textureFile"": ""fits_27.png"",
    ""requiredAchievement"": ""WellRestedBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 28,
    ""textureFile"": ""fits_28.png"",
    ""requiredAchievement"": ""MedievalHistoryBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 29,
    ""textureFile"": ""fits_29.png"",
    ""requiredAchievement"": ""JesterBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 30,
    ""textureFile"": ""fits_30.png"",
    ""requiredAchievement"": ""LastResortBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 31,
    ""textureFile"": ""fits_31.png"",
    ""requiredAchievement"": ""HangGlidingBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 32,
    ""textureFile"": ""fits_32.png"",
    ""requiredAchievement"": ""ExorcistBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""fits"",
    ""index"": 33,
    ""textureFile"": ""fits_33.png"",
    ""requiredAchievement"": ""RuleZeroBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 0,
    ""textureFile"": ""hats_0.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 1,
    ""textureFile"": ""hats_1.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 2,
    ""textureFile"": ""hats_2.png"",
    ""requiredAchievement"": ""TrailblazerBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 3,
    ""textureFile"": ""hats_3.png"",
    ""requiredAchievement"": ""BingBongBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 4,
    ""textureFile"": ""hats_4.png"",
    ""requiredAchievement"": ""BeachcomberBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 5,
    ""textureFile"": ""hats_5.png"",
    ""requiredAchievement"": ""AlpinistBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 6,
    ""textureFile"": ""hats_6.png"",
    ""requiredAchievement"": ""ClutchBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 7,
    ""textureFile"": ""hats_7.png"",
    ""requiredAchievement"": ""FirstAidBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 8,
    ""textureFile"": ""hats_8.png"",
    ""requiredAchievement"": ""NaturalistBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 9,
    ""textureFile"": ""hats_9.png"",
    ""requiredAchievement"": ""MycologyBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 10,
    ""textureFile"": ""hats_10.png"",
    ""requiredAchievement"": ""AnimalSerenadingBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 11,
    ""textureFile"": ""hats_11.png"",
    ""requiredAchievement"": ""SpeedClimberBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 12,
    ""textureFile"": ""hats_12.png"",
    ""requiredAchievement"": ""PeakBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 13,
    ""textureFile"": ""hats_13.png"",
    ""requiredAchievement"": ""AscenderBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 14,
    ""textureFile"": ""hats_14.png"",
    ""requiredAchievement"": ""EnduranceBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 15,
    ""textureFile"": ""hats_15.png"",
    ""requiredAchievement"": ""CookingBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 16,
    ""textureFile"": ""hats_16.png"",
    ""requiredAchievement"": ""EsotericaBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 17,
    ""textureFile"": ""hats_17.png"",
    ""requiredAchievement"": ""LoneWolfBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 18,
    ""textureFile"": ""hats_18.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""Crown"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 19,
    ""textureFile"": ""hats_19.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""Goat"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 20,
    ""textureFile"": ""hats_20.png"",
    ""requiredAchievement"": ""NomadBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 21,
    ""textureFile"": ""hats_21.png"",
    ""requiredAchievement"": ""UltimateBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 22,
    ""textureFile"": ""hats_22.png"",
    ""requiredAchievement"": ""NeedlepointBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 23,
    ""textureFile"": ""hats_23.png"",
    ""requiredAchievement"": ""CoolCucumberBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 24,
    ""textureFile"": ""hats_24.png"",
    ""requiredAchievement"": ""TwentyFourKaratBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 25,
    ""textureFile"": ""hats_25.png"",
    ""requiredAchievement"": ""DaredevilBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 26,
    ""textureFile"": ""hats_26.png"",
    ""requiredAchievement"": ""AeronauticsBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 27,
    ""textureFile"": ""hats_27.png"",
    ""requiredAchievement"": ""UndeadEncounterBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 28,
    ""textureFile"": ""hats_28.png"",
    ""requiredAchievement"": ""WebSecurityBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 29,
    ""textureFile"": ""hats_29.png"",
    ""requiredAchievement"": ""AdvancedMycologyBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 30,
    ""textureFile"": ""hats_30.png"",
    ""requiredAchievement"": ""ForestryBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 31,
    ""textureFile"": ""hats_31.png"",
    ""requiredAchievement"": ""TreadLightlyBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 32,
    ""textureFile"": ""hats_32.png"",
    ""requiredAchievement"": ""DisasterResponseBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 33,
    ""textureFile"": ""hats_33.png"",
    ""requiredAchievement"": ""CompetitiveEatingBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 34,
    ""textureFile"": ""hats_34.png"",
    ""requiredAchievement"": ""MycoacrobaticsBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 35,
    ""textureFile"": ""hats_35.png"",
    ""requiredAchievement"": ""CryptogastronomyBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 36,
    ""textureFile"": ""hats_36.png"",
    ""requiredAchievement"": ""WandererBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 37,
    ""textureFile"": ""hats_37.png"",
    ""requiredAchievement"": ""JesterBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 38,
    ""textureFile"": ""hats_38.png"",
    ""requiredAchievement"": ""WellRestedBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 39,
    ""textureFile"": ""hats_39.png"",
    ""requiredAchievement"": ""ArcheryBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 40,
    ""textureFile"": ""hats_40.png"",
    ""requiredAchievement"": ""LastResortBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 41,
    ""textureFile"": ""hats_41.png"",
    ""requiredAchievement"": ""MedievalHistoryBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 42,
    ""textureFile"": ""hats_42.png"",
    ""requiredAchievement"": ""BellringerBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 43,
    ""textureFile"": ""hats_43.png"",
    ""requiredAchievement"": ""ExorcistBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""hats"",
    ""index"": 44,
    ""textureFile"": ""hats_44.png"",
    ""requiredAchievement"": ""RuleZeroBadge"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""sashes"",
    ""index"": 0,
    ""textureFile"": ""sashes_0.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""sashes"",
    ""index"": 1,
    ""textureFile"": ""sashes_1.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": true,
    ""requiredAscent"": 1,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""sashes"",
    ""index"": 2,
    ""textureFile"": ""sashes_2.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": true,
    ""requiredAscent"": 2,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""sashes"",
    ""index"": 3,
    ""textureFile"": ""sashes_3.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": true,
    ""requiredAscent"": 3,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""sashes"",
    ""index"": 4,
    ""textureFile"": ""sashes_4.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": true,
    ""requiredAscent"": 4,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""sashes"",
    ""index"": 5,
    ""textureFile"": ""sashes_5.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": true,
    ""requiredAscent"": 5,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""sashes"",
    ""index"": 6,
    ""textureFile"": ""sashes_6.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": true,
    ""requiredAscent"": 6,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""sashes"",
    ""index"": 7,
    ""textureFile"": ""sashes_7.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": true,
    ""requiredAscent"": 7,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""sashes"",
    ""index"": 8,
    ""textureFile"": ""sashes_8.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": true,
    ""requiredAscent"": 8,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""sashes"",
    ""index"": 9,
    ""textureFile"": ""sashes_9.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": true,
    ""requiredAscent"": 9,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""medals"",
    ""index"": 0,
    ""textureFile"": ""medals_0.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""medals"",
    ""index"": 1,
    ""textureFile"": ""medals_1.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""None"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""special"",
    ""index"": 0,
    ""textureFile"": ""special_0.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""Goat"",
    ""isBlank"": false,
    ""testLocked"": false
  },
  {
    ""slot"": ""special"",
    ""index"": 1,
    ""textureFile"": ""special_1.png"",
    ""requiredAchievement"": ""NONE"",
    ""requiredSteamStat"": ""NONE"",
    ""requiredSteamStatValue"": 1,
    ""requiresAscent"": false,
    ""requiredAscent"": 0,
    ""customRequirement"": ""Crown"",
    ""isBlank"": false,
    ""testLocked"": false
  }
]";

        public const string AchievementsJson = @"[
  {
    ""achievementType"": ""KnotTyingBadge"",
    ""kind"": ""runbased"",
    ""statType"": ""RopePlaced"",
    ""requiredValue"": 100
  },
  {
    ""achievementType"": ""ClutchBadge"",
    ""kind"": ""runbased"",
    ""statType"": ""ScoutsResurrected"",
    ""requiredValue"": 3
  },
  {
    ""achievementType"": ""PlundererBadge"",
    ""kind"": ""runbased"",
    ""statType"": ""LuggageOpened"",
    ""requiredValue"": 15
  },
  {
    ""achievementType"": ""FirstAidBadge"",
    ""kind"": ""runbased"",
    ""statType"": ""FriendsHealedAmount"",
    ""requiredValue"": 20
  },
  {
    ""achievementType"": ""JesterBadge"",
    ""kind"": ""runbased"",
    ""statType"": ""ClownLuggageOpened"",
    ""requiredValue"": 2
  },
  {
    ""achievementType"": ""ArcheryBadge"",
    ""kind"": ""runbased"",
    ""statType"": ""ArrowsRemoved"",
    ""requiredValue"": 10
  },
  {
    ""achievementType"": ""ForestryBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_Forestry"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""TreadLightlyBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_TreadLightly"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""WebSecurityBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_WebSecurity"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""UndeadEncounterBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_UndeadEncounter"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""AdvancedMycologyBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_AdvancedMycology"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""DisasterResponseBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_DisasterResponse"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""CalciumIntakeBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""DamageBlockedByMilk"",
    ""requiredValue"": 100
  },
  {
    ""achievementType"": ""CompetitiveEatingBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_CompetitiveEating"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""AppliedEsotericaBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_AppliedEsoterica"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""MycoacrobaticsBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_Mycoacrobatics"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""CryptogastronomyBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_Cryptogastronomy"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""WandererBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_Wanderer"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""BellringerBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_Bellringer"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""WellRestedBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_WellRested"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""JesterBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_Jester"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""HangGlidingBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_HangGliding"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""MedievalHistoryBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_MedievalHistory"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""LastResortBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_LastResort"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""ExorcistBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_Exorcist"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""ArcheryBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_Archery"",
    ""requiredValue"": 1
  },
  {
    ""achievementType"": ""RuleZeroBadge"",
    ""kind"": ""steamstat"",
    ""statType"": ""GotBadge_RuleZero"",
    ""requiredValue"": 1
  }
]";
    }
}
